"""set_user_fks_to_set_null

Revision ID: 33007463ffaa
Revises: c5c32f50ce92
Create Date: 2026-03-19 16:45:19.876721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33007463ffaa'
down_revision: Union[str, Sequence[str], None] = 'c5c32f50ce92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blockers', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('blockers_created_by_fkey', 'blockers', type_='foreignkey')
    op.create_foreign_key(None, 'blockers', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('standups', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('standups_created_by_fkey', 'standups', type_='foreignkey')
    op.create_foreign_key(None, 'standups', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('tasks', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tasks', 'assignee_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('tasks_assignee_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_created_by_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('tickets', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tickets', 'assignee_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('tickets_assignee_id_fkey', 'tickets', type_='foreignkey')
    op.drop_constraint('tickets_created_by_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tickets', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_created_by_fkey', 'tickets', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tickets_assignee_id_fkey', 'tickets', 'users', ['assignee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tickets', 'assignee_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tickets', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_created_by_fkey', 'tasks', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tasks_assignee_id_fkey', 'tasks', 'users', ['assignee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tasks', 'assignee_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tasks', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'standups', type_='foreignkey')
    op.create_foreign_key('standups_created_by_fkey', 'standups', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.alter_column('standups', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'blockers', type_='foreignkey')
    op.create_foreign_key('blockers_created_by_fkey', 'blockers', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.alter_column('blockers', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
