"""cascade_delete_blockers_on_ticket_delete

Revision ID: 708b89079306
Revises: 7dee2f020f0e
Create Date: 2026-03-14 19:13:24.578945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708b89079306'
down_revision: Union[str, Sequence[str], None] = '7dee2f020f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blockers_ticket_id_fkey', 'blockers', type_='foreignkey')
    op.create_foreign_key(None, 'blockers', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blockers', type_='foreignkey')
    op.create_foreign_key('blockers_ticket_id_fkey', 'blockers', 'tickets', ['ticket_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
