"""add standup blocker ticket task tables

Revision ID: a0c8b38c35cb
Revises: b8feae0d2f72
Create Date: 2026-02-19 12:52:59.926198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0c8b38c35cb'
down_revision: Union[str, Sequence[str], None] = 'b8feae0d2f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('today', sa.Text(), nullable=False),
    sa.Column('yesterday', sa.Text(), nullable=True),
    sa.Column('blocker_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('standup_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'created_by', 'standup_date', name='uq_standup_per_user_per_day_per_org')
    )
    op.create_index(op.f('ix_standups_created_by'), 'standups', ['created_by'], unique=False)
    op.create_index(op.f('ix_standups_organization_id'), 'standups', ['organization_id'], unique=False)
    op.create_index(op.f('ix_standups_standup_date'), 'standups', ['standup_date'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'COMPLETED', name='ticket_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='ticket_priority'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blockers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='blocker_status'), server_default='open', nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockers_assignee_id'), 'blockers', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_blockers_created_by'), 'blockers', ['created_by'], unique=False)
    op.create_index(op.f('ix_blockers_organization_id'), 'blockers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_blockers_status'), 'blockers', ['status'], unique=False)
    op.create_index(op.f('ix_blockers_ticket_id'), 'blockers', ['ticket_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='task_status'), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('memberships')
    op.drop_constraint('organizations_created_by_fkey', 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('org_role', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('scrum_role', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.drop_constraint('fk_users_current_organization_id', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'current_organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_current_organization_id', 'users', 'organizations', ['current_organization_id'], ['id'])
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_column('users', 'scrum_role')
    op.drop_column('users', 'org_role')
    op.drop_column('users', 'organization_id')
    op.drop_column('users', 'avatar_url')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key('organizations_created_by_fkey', 'organizations', 'users', ['created_by'], ['id'])
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('org_role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('scrum_role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("org_role::text = ANY (ARRAY['admin'::character varying, 'member'::character varying]::text[])", name='ck_membership_org_role'),
    sa.CheckConstraint("scrum_role::text = ANY (ARRAY['scrum_master'::character varying, 'product_owner'::character varying, 'developer'::character varying]::text[])", name='ck_membership_scrum_role'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='memberships_organization_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='memberships_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='memberships_pkey'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_memberships_user_org')
    )
    op.drop_table('tasks')
    op.drop_index(op.f('ix_blockers_ticket_id'), table_name='blockers')
    op.drop_index(op.f('ix_blockers_status'), table_name='blockers')
    op.drop_index(op.f('ix_blockers_organization_id'), table_name='blockers')
    op.drop_index(op.f('ix_blockers_created_by'), table_name='blockers')
    op.drop_index(op.f('ix_blockers_assignee_id'), table_name='blockers')
    op.drop_table('blockers')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_standups_standup_date'), table_name='standups')
    op.drop_index(op.f('ix_standups_organization_id'), table_name='standups')
    op.drop_index(op.f('ix_standups_created_by'), table_name='standups')
    op.drop_table('standups')
    # ### end Alembic commands ###
