"""make_blocker_ticket_id_required

Revision ID: a115884df422
Revises: 708b89079306
Create Date: 2026-03-19 15:40:50.590437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a115884df422'
down_revision: Union[str, Sequence[str], None] = '708b89079306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blockers', 'ticket_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blockers', 'ticket_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
