"""make_assignee_id_required_tickets_tasks

Revision ID: c5c32f50ce92
Revises: 67f122527c08
Create Date: 2026-03-19 15:59:01.486809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c32f50ce92'
down_revision: Union[str, Sequence[str], None] = '67f122527c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'assignee_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('tasks_assignee_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tickets', 'assignee_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('tickets_assignee_id_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['assignee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_assignee_id_fkey', 'tickets', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tickets', 'assignee_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_assignee_id_fkey', 'tasks', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tasks', 'assignee_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
